"""Smoke test for the (mostly autogenerated) Def-node wrappers.

Constructs one instance of every core node reachable from a bare `World` and
invokes a method or two, so a broken or missing binding surfaces immediately.

Deliberately not exercised: nodes that need rewrite/lattice/plugin state beyond
a smoke test (`Axm`, `Proxy`, `Merge`, `Match`, `Reform`, `Rule`, `UMax`,
`UInc`) and the abstract bases reached only via their subclasses (`Def`, `Prod`,
`Seq`, `Bound`, `Ext`).
"""
from __future__ import annotations

import mim


def _every_node(w) -> list[tuple[mim.Def, type]]:
    b, i8 = w.type_bool(), w.type_i8()
    i8v, tt, n4 = w.lit_i8(7), w.lit_tt(), w.lit_nat(4)
    lam = w.mut_con([b, i8])
    var = lam.var()
    meet, join = w.meet([b, i8]), w.join([b, i8])
    return [
        (w.univ(), mim.Univ),
        (w.type(w.lit_univ_0()), mim.Type),
        (w.type_nat(), mim.Nat),
        (i8v, mim.Lit),
        (b, mim.App),
        (w.cn([b, i8]), mim.Pi),
        (lam, mim.Lam),
        (var, mim.Var),
        (w.sigma([b, i8]), mim.Sigma),
        (w.tuple([tt, i8v]), mim.Tuple),
        (w.arr(n4, i8), mim.Arr),
        (w.pack(n4, i8v), mim.Pack),
        (w.extract(var, 0), mim.Extract),
        (w.insert(var, 1, i8v), mim.Insert),
        (getattr(w, "global")(i8, False), mim.Global),
        (meet, mim.Meet),
        (join, mim.Join),
        (w.bot(i8), mim.Bot),
        (w.top(i8), mim.Top),
        (w.mut_hole(i8), mim.Hole),
        (w.uniq(i8v), mim.Uniq),
        (w.inj(join, tt), mim.Inj),
        (w.split(meet, tt), mim.Split),
    ]


def test_every_node_constructs(world):
    for node, cls in _every_node(world):
        assert isinstance(node, cls), f"expected {cls.__name__}, got {type(node).__name__}"
        assert isinstance(node, mim.Def)
        assert isinstance(node.world(), mim.World)  # a bound method round-trips


def test_node_methods(world):
    m = world.mut_con([world.type_bool(), world.type_i8()]).set("f")
    assert m.var().num_projs() == 2
    assert len(m.var().projs(2)) == 2

    lit = world.lit_i8(0)
    lit.dump()  # does not raise
    assert isinstance(lit.type(), mim.Def)
